site:
  name: Epheia
  site: 'https://epheia.ai'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: "Epheia - Pioneering Ephemeral Zero-Retention AI"
    template: '%s — Epheia'
  description: "Empowering healthcare with adaptive AI that processes sensitive data in real-time"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Epheia
    type: website
    images:
      - url: '~/assets/images/og-image.jpg'
        width: 1200
        height: 630
        alt: 'Epheia - Pioneering Ephemeral Zero-Retention AI'
  twitter:
    handle: '@epheiaai'  # Update this to your actual Twitter handle
    site: '@epheiaai'    # Update this to your actual Twitter handle
    cardType: summary_large_image
    # Add Twitter image
    image: '~/assets/images/og-image.jpg'
    imageAlt: 'Epheia - Pioneering Ephemeral Zero-Retention AI'